### ISSUE TITLE
[Bug] Items get stuck when cycling item hotbar

### ISSUE THREAD

**Issue by Sranshaft** [grompe/BTWTweak#6]
When cycling the items in the hotbar some times an item will get removed from the inventory and will appear stuck to the cursor when opening the inventory. 

I'm still trying to track down the particulars in order to reproduce it consistently but it seems to happen more often when all spaces in the inventory's column are occupied.

**Comment by grompe** [comment]
Yep, had this happen occasionally, not sure what exactly is causing it.

**Comment by grompe** [comment]
Mostly fixed by not attempting to exchange empty slots. Now the only way this could happen is with network lag occuring in the middle of exchanging process.
