### ISSUE TITLE
Feature request: Disable microblock merging at the saw

### ISSUE THREAD

**Issue by Sranshaft** [grompe/BTWTweak#8]
Love the new microblock combining feature but find it an annoyance when using my saw setup to cut them. Any chance you could make it so it doesn't combine microblocks if sneaking?

**Comment by grompe** [comment]
It should only be a problem if you place microblocks at the saw directly. Try putting them at angle or on a side of another block.

I don't like the idea of disabling combining when sneaking. Perhaps disabling it near the saw would be good.

**Comment by Sranshaft** [comment]
The problem is I have a line of four saws for quickly going through stacks of blocks and placing microblocks at an angle can be a huge annoyance.

Disabling it while near saw sounds good to me.
